# -*- coding: utf-8 -*-
"""CSAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ou1jFE1Gr1Uv6tPC0_MEOs1m5WpnJzZ
"""

def is_binary(s):
    return all(char in "01" for char in s)


def main():
    print("======================================")
    print(" Finite Automaton Simulator")
    print(" Language: Binary strings that end with 101")
    print(" Type 'exit' to terminate the program")
    print("======================================\n")

    while True:
        user_input = input("Enter a binary string: ")

        if user_input.lower() == "exit":
            print("\nProgram terminated.")
            break

        # error handling
        if not is_binary(user_input):
            print("Error: Input must contain only 0 and 1.\n")
            continue

        if user_input.endswith("101"):
            print("Result: ACCEPTED\n")
        else:
            print("Result: NOT ACCEPTED\n")


if __name__ == "__main__":
    main()

def is_binary(s):
    return all(c in "01" for c in s)


def describe_string(s):
    # Most specific conditions first
    if s.startswith("101") and s.endswith("00"):
        return "Starts with 101 and ends with 00"

    if "111" in s and s.endswith("011"):
        return "At least three consecutive 1's and ends with 011"

    if s.count("1") >= 3 and "00" in s:
        return "At least three 1's and 2 consecutive 0's"

    if s.endswith("1") and s.count("0") % 2 == 1:
        return "Ends with 1 and has an odd number of 0's"

    if s.endswith("0") and s.count("0") % 2 == 0:
        return "Ends with 0 and even number of 0's"

    if s.startswith("101"):
        return "Starts with 101"

    if s.endswith("101"):
        return "Ends with 101"

    if "000" in s:
        return "At least three consecutive 0's"

    if s.count("1") >= 3:
        return "At least three 1's"

    if s.count("1") % 2 == 1:
        return "Odd number of 1's"

    if s.count("0") % 2 == 1:
        return "Odd number of 0's"

    if s.count("1") > 0 and s.count("1") % 2 == 0:
        return "Even number of 1's"

    if s.count("0") > 0 and s.count("0") % 2 == 0:
        return "Even number of 0's"

    return "Binary string"


def main():
    print("====================================")
    print("Finite Automaton Mini Project")
    print("Language: String that ends with 101")
    print("Type 'exit' to stop")
    print("====================================\n")

    while True:
        user_input = input("Input: ").strip()

        if user_input.lower() == "exit":
            print("\nProgram terminated.")
            break

        if not user_input:
            print("Error: Empty input\n")
            continue

        if not is_binary(user_input):
            print("Error: Only 0 and 1 allowed\n")
            continue

        description = describe_string(user_input)

        print(f"Inputted String: {description}")

        if user_input.endswith("101"):
            print("ACCEPTED\n")
        else:
            print("But not Ends with 101")
            print("NOT ACCEPTED\n")


if __name__ == "__main__":
    main()